In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
num1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(num1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Check Dimension of array**

In [11]:
a = np.array(2)
b = np.array([0,1,2])
c = np.array([[1,2,3],[2,3,4]])
d = np.array([[[4,2,1],[3,44,56],[3,4,5]]])
e = np.array([[[[6,7,4],[4,5,6],[4,5,9],[67,8,6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


0
1
2
3
4


**Higher Dimentional Array**

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8],ndmin = 8)
print(arr)
print("Number of dimension : ",arr.ndim)

[[[[[[[[1 2 3 4 5 6 7 8]]]]]]]]
Number of dimension :  8


**Show array index value**

In [14]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4])

5


**Get 3th and 4th element and add them**

In [16]:
arr = np.array([10,12,14,16,18])
print(arr[3] + arr[4])
print(arr[3] * arr[4])
print(arr[4] - arr[3])

34
288
2


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element on 1st dim : ",arr[0,1])

2nd element on 1st dim :  2


In [19]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,2]+ arr[1,2])

9


In [20]:
arr = np.array([[[1,2,3],[4,6,9]],[[1,4,5],[4,7,1]]])
print(arr[1,1,1])

7


**Negative Indexing**

In [21]:
arr = np.array([[[1,2,3],[4,6,9]],[[1,4,5],[4,7,1]]])
print("2nd element of last dim : ", arr[1,-1,-2])

2nd element of last dim :  7


**Slicing Array**

In [25]:
arr = np.array([1,2,3,4,5,6,7,])
print(arr[3:6])
print(arr[::])
print(arr[1::3])
print(arr[5:])

[4 5 6]
[1 2 3 4 5 6 7]
[2 5]
[6 7]
